package ModifiedHangman;


/**
* ModifiedHangman/AdminService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AdminService.idl
* Saturday, April 26, 2025 3:26:26 AM SGT
*/

public interface AdminService extends AdminServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminService
