package ModifiedHangman;


import java.util.List;

/**
* ModifiedHangman/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AdminService.idl
* Saturday, April 26, 2025 3:26:26 AM SGT
*/

public interface AdminServiceOperations 
{
  boolean create_player (String username, String password, String token);
  boolean update_player (String username, String new_password, String token);
  boolean delete_player (String username, String token);
  Player search_player (String keyword, String token);
  List<Player> get_all_players();
  void set_waiting_time (int seconds, String token);
  void set_round_duration (int seconds, String token);
  int get_waiting_time (String token);
  int get_round_duration (String token);
} // interface AdminServiceOperations
