package ModifiedHangman;

/**
* ModifiedHangman/AdminNotLoggedInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AdminService.idl
* Friday, May 16, 2025 12:00:07 AM SGT
*/

public final class AdminNotLoggedInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.AdminNotLoggedInException value = null;

  public AdminNotLoggedInExceptionHolder ()
  {
  }

  public AdminNotLoggedInExceptionHolder (ModifiedHangman.AdminNotLoggedInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.AdminNotLoggedInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.AdminNotLoggedInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.AdminNotLoggedInExceptionHelper.type ();
  }

}
