package ModifiedHangman;


/**
* ModifiedHangman/AdminNotLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AdminService.idl
* Thursday, May 15, 2025 9:19:34 PM SGT
*/

public final class AdminNotLoggedInException extends org.omg.CORBA.UserException
{
  public String message = null;

  public AdminNotLoggedInException ()
  {
    super(AdminNotLoggedInExceptionHelper.id());
  } // ctor

  public AdminNotLoggedInException (String _message)
  {
    super(AdminNotLoggedInExceptionHelper.id());
    message = _message;
  } // ctor


  public AdminNotLoggedInException (String $reason, String _message)
  {
    super(AdminNotLoggedInExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class AdminNotLoggedInException
