package ModifiedHangman;


/**
* ModifiedHangman/AdminService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/User/IdeaProjects/9322-Team05_FinProject/CORBA_IDLs/ModifiedHangman/AdminService.idl
* Thursday, May 15, 2025 12:11:02 PM SGT
*/

public interface AdminService extends AdminServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminService
