package ModifiedHangman;

/**
* ModifiedHangman/AdminServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AdminService.idl
* Thursday, May 15, 2025 9:19:34 PM SGT
*/

public final class AdminServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.AdminService value = null;

  public AdminServiceHolder ()
  {
  }

  public AdminServiceHolder (ModifiedHangman.AdminService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.AdminServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.AdminServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.AdminServiceHelper.type ();
  }

}
