package ModifiedHangman;


/**
* ModifiedHangman/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/User/IdeaProjects/9322-Team05_FinProject/CORBA_IDLs/ModifiedHangman/AdminService.idl
* Thursday, May 15, 2025 12:11:02 PM SGT
*/

public interface AdminServiceOperations 
{
  void create_player (String username, String password, String token) throws ModifiedHangman.AdminNotLoggedInException;
  void update_player (String username, String new_password, String token) throws ModifiedHangman.AdminNotLoggedInException;
  void delete_player (String username, String token) throws ModifiedHangman.AdminNotLoggedInException;
  ModifiedHangman.Player search_player (String keyword, String token) throws ModifiedHangman.AdminNotLoggedInException;
  ModifiedHangman.Player[] get_all_player (String token) throws ModifiedHangman.AdminNotLoggedInException;
  void set_waiting_time (int seconds, String token) throws ModifiedHangman.AdminNotLoggedInException;
  void set_round_duration (int seconds, String token) throws ModifiedHangman.AdminNotLoggedInException;
  int get_waiting_time (String token) throws ModifiedHangman.AdminNotLoggedInException;
  int get_round_duration (String token) throws ModifiedHangman.AdminNotLoggedInException;
} // interface AdminServiceOperations
