package ModifiedHangman;


/**
* ModifiedHangman/AttemptedLetter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Saturday, April 26, 2025 3:25:42 AM SGT
*/

public final class AttemptedLetter implements org.omg.CORBA.portable.IDLEntity
{
  public String letter = null;
  public boolean isLetterCorrect = false;

  public AttemptedLetter ()
  {
  } // ctor

  public AttemptedLetter (String _letter, boolean _isLetterCorrect)
  {
    letter = _letter;
    isLetterCorrect = _isLetterCorrect;
  } // ctor

} // class AttemptedLetter
