package ModifiedHangman;

/**
* ModifiedHangman/AttemptedLetterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Saturday, April 26, 2025 3:25:42 AM SGT
*/

public final class AttemptedLetterHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.AttemptedLetter value = null;

  public AttemptedLetterHolder ()
  {
  }

  public AttemptedLetterHolder (ModifiedHangman.AttemptedLetter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.AttemptedLetterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.AttemptedLetterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.AttemptedLetterHelper.type ();
  }

}
