package ModifiedHangman;


/**
* ModifiedHangman/AttemptedLetterHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Friday, May 16, 2025 12:00:04 AM SGT
*/

abstract public class AttemptedLetterHelper
{
  private static String  _id = "IDL:ModifiedHangman/AttemptedLetter:1.0";

  public static void insert (org.omg.CORBA.Any a, ModifiedHangman.AttemptedLetter that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ModifiedHangman.AttemptedLetter extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_char);
          _members0[0] = new org.omg.CORBA.StructMember (
            "letter",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[1] = new org.omg.CORBA.StructMember (
            "isLetterCorrect",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ModifiedHangman.AttemptedLetterHelper.id (), "AttemptedLetter", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ModifiedHangman.AttemptedLetter read (org.omg.CORBA.portable.InputStream istream)
  {
    ModifiedHangman.AttemptedLetter value = new ModifiedHangman.AttemptedLetter ();
    value.letter = istream.read_char ();
    value.isLetterCorrect = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ModifiedHangman.AttemptedLetter value)
  {
    ostream.write_char (value.letter);
    ostream.write_boolean (value.isLetterCorrect);
  }

}
