package ModifiedHangman;


/**
* ModifiedHangman/AttemptedLetter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 10:54:55 PM SGT
*/

public final class AttemptedLetter implements org.omg.CORBA.portable.IDLEntity
{
  public char letter = (char)0;
  public boolean isLetterCorrect = false;

  public AttemptedLetter ()
  {
  } // ctor

  public AttemptedLetter (char _letter, boolean _isLetterCorrect)
  {
    letter = _letter;
    isLetterCorrect = _isLetterCorrect;
  } // ctor

} // class AttemptedLetter
