package ModifiedHangman;


/**
* ModifiedHangman/AuthenticationServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AuthenticationService.idl
* Thursday, May 15, 2025 10:54:53 PM SGT
*/

public interface AuthenticationServiceOperations 
{
  String login (String username, String password) throws ModifiedHangman.LogInException;
  void logout (String token) throws ModifiedHangman.PlayerNotLoggedInException;
  void registerCallback (ModifiedHangman.ClientCallback callback, String token) throws ModifiedHangman.PlayerNotLoggedInException;
} // interface AuthenticationServiceOperations
