module ModifiedHangman {

  exception LogInException {
    string message;
  };

  exception PlayerNotLoggedInException {
    string message;
  };

  interface ClientCallback {
    void notify(in string message);
  };

  interface AuthenticationService {

    string login(in string username, in string password)
      raises (LogInException);

    void logout(in string token)
      raises (PlayerNotLoggedInException);

    void registerCallback(in ClientCallback callback, in string token)
      raises (PlayerNotLoggedInException);
  };

};
