package ModifiedHangman;


/**
* ModifiedHangman/AuthenticationService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AuthenticationService.idl
* Thursday, May 15, 2025 9:19:36 PM SGT
*/

public interface AuthenticationService extends AuthenticationServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AuthenticationService
