package ModifiedHangman;


/**
* ModifiedHangman/AuthenticationServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AuthenticationService.idl
* Saturday, April 26, 2025 3:26:15 AM SGT
*/

abstract public class AuthenticationServiceHelper
{
  private static String  _id = "IDL:ModifiedHangman/AuthenticationService:1.0";

  public static void insert (org.omg.CORBA.Any a, ModifiedHangman.AuthenticationService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ModifiedHangman.AuthenticationService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ModifiedHangman.AuthenticationServiceHelper.id (), "AuthenticationService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ModifiedHangman.AuthenticationService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (AuthenticationServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ModifiedHangman.AuthenticationService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ModifiedHangman.AuthenticationService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ModifiedHangman.AuthenticationService)
      return (ModifiedHangman.AuthenticationService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ModifiedHangman.AuthenticationServiceStub stub = new ModifiedHangman.AuthenticationServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ModifiedHangman.AuthenticationService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ModifiedHangman.AuthenticationService)
      return (ModifiedHangman.AuthenticationService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ModifiedHangman.AuthenticationServiceStub stub = new ModifiedHangman.AuthenticationServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
