package ModifiedHangman;

/**
* ModifiedHangman/AuthenticationServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AuthenticationService.idl
* Friday, May 16, 2025 12:00:00 AM SGT
*/

public final class AuthenticationServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.AuthenticationService value = null;

  public AuthenticationServiceHolder ()
  {
  }

  public AuthenticationServiceHolder (ModifiedHangman.AuthenticationService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.AuthenticationServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.AuthenticationServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.AuthenticationServiceHelper.type ();
  }

}
