package ModifiedHangman;


/**
* ModifiedHangman/AuthenticationServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AuthenticationService.idl
* Saturday, April 26, 2025 3:26:15 AM SGT
*/

public interface AuthenticationServiceOperations 
{

  // returns a token string
  String login (String username, String password) throws ModifiedHangman.LogInException;
  void logout (String token) throws ModifiedHangman.PlayerNotLoggedInException;
} // interface AuthenticationServiceOperations
