package ModifiedHangman;


/**
* ModifiedHangman/AuthenticationService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AuthenticationService.idl
* Saturday, April 26, 2025 3:26:15 AM SGT
*/

public interface AuthenticationService extends AuthenticationServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AuthenticationService
