package ModifiedHangman;


/**
* ModifiedHangman/AuthenticationServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AuthenticationService.idl
* Friday, May 16, 2025 12:00:00 AM SGT
*/

public interface AuthenticationServiceOperations 
{
  String login (String username, String password) throws ModifiedHangman.LogInException;
  void logout (String token) throws ModifiedHangman.PlayerNotLoggedInException;
  void registerCallback (ModifiedHangman.ClientCallback callback, String token) throws ModifiedHangman.PlayerNotLoggedInException;
} // interface AuthenticationServiceOperations
