package ModifiedHangman;


/**
* ModifiedHangman/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 10:54:55 PM SGT
*/

public interface ClientCallbackOperations 
{
  void startRound (int wordLength, int roundNumber);
  void startGameFailed ();
  void endGame (ModifiedHangman.GameResult gameResultData);
  void endRound (ModifiedHangman.RoundResult roundResultData);
  void proceedToNextRound (int wordLength, int roundNUmber);
} // interface ClientCallbackOperations
