package ModifiedHangman;


/**
 * ModifiedHangman/ClientCallbackPOA.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from ModifiedHangman/GameService.idl
 * Thursday, May 15, 2025 9:19:59 PM SGT
 */

public abstract class ClientCallbackPOA extends org.omg.PortableServer.Servant
        implements ModifiedHangman.ClientCallbackOperations, org.omg.CORBA.portable.InvokeHandler
{

    // Constructors

    private static java.util.Hashtable _methods = new java.util.Hashtable ();
    static
    {
        _methods.put ("startRound", new java.lang.Integer (0));
        _methods.put ("startGameFailed", new java.lang.Integer (1));
        _methods.put ("endGame", new java.lang.Integer (2));
        _methods.put ("endRound", new java.lang.Integer (3));
        _methods.put ("proceedToNextRound", new java.lang.Integer (4));
        _methods.put ("notifySessionInvalidated", new java.lang.Integer (5)); // ADDED: New method for session invalidation
    }

    public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                                        org.omg.CORBA.portable.InputStream in,
                                                        org.omg.CORBA.portable.ResponseHandler $rh)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
        if (__method == null)
            throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

        switch (__method.intValue ())
        {
            case 0:  // ModifiedHangman/ClientCallback/startRound
            {
                int wordLength = in.read_long ();
                int roundNumber = in.read_long ();
                this.startRound (wordLength, roundNumber);
                out = $rh.createReply();
                break;
            }

            case 1:  // ModifiedHangman/ClientCallback/startGameFailed
            {
                this.startGameFailed ();
                out = $rh.createReply();
                break;
            }

            case 2:  // ModifiedHangman/ClientCallback/endGame
            {
                ModifiedHangman.GameResult gameResult = ModifiedHangman.GameResultHelper.read (in);
                this.endGame (gameResult);
                out = $rh.createReply();
                break;
            }

            case 3:  // ModifiedHangman/ClientCallback/endRound
            {
                ModifiedHangman.RoundResult roundResult = ModifiedHangman.RoundResultHelper.read (in);
                this.endRound (roundResult);
                out = $rh.createReply();
                break;
            }

            case 4:  // ModifiedHangman/ClientCallback/proceedToNextRound
            {
                int wordLength = in.read_long ();
                this.proceedToNextRound (wordLength);
                out = $rh.createReply();
                break;
            }

            case 5:  // ModifiedHangman/ClientCallback/notifySessionInvalidated // ADDED: New case for session invalidation
            {
                String reason = in.read_string (); // Read the string argument
                ((ModifiedHangman.ClientCallbackOperations)this).notifySessionInvalidated (reason); // Cast to interface and call method
                out = $rh.createReply();
                break;
            }

            default:
                throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        return out;
    } // _invoke

    // Type-specific CORBA::Object operations
    private static String[] __ids = {
            "IDL:ModifiedHangman/ClientCallback:1.0"};

    public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
    {
        return (String[])__ids.clone ();
    }

    public ClientCallback _this()
    {
        return ClientCallbackHelper.narrow(
                super._this_object());
    }

    public ClientCallback _this(org.omg.CORBA.ORB orb)
    {
        return ClientCallbackHelper.narrow(
                super._this_object(orb));
    }


} // class ClientCallbackPOA