package ModifiedHangman;


/**
* ModifiedHangman/ClientCallbackHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/User/IdeaProjects/9322-Team05_FinProject/CORBA_IDLs/ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 12:11:32 PM SGT
*/

abstract public class ClientCallbackHelper
{
  private static String  _id = "IDL:ModifiedHangman/ClientCallback:1.0";

  public static void insert (org.omg.CORBA.Any a, ModifiedHangman.ClientCallback that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ModifiedHangman.ClientCallback extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ModifiedHangman.ClientCallbackHelper.id (), "ClientCallback");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ModifiedHangman.ClientCallback read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClientCallbackStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ModifiedHangman.ClientCallback value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ModifiedHangman.ClientCallback narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ModifiedHangman.ClientCallback)
      return (ModifiedHangman.ClientCallback)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ModifiedHangman._ClientCallbackStub stub = new ModifiedHangman._ClientCallbackStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ModifiedHangman.ClientCallback unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ModifiedHangman.ClientCallback)
      return (ModifiedHangman.ClientCallback)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ModifiedHangman._ClientCallbackStub stub = new ModifiedHangman._ClientCallbackStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
