package ModifiedHangman;


/**
* ModifiedHangman/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Friday, May 16, 2025 12:00:04 AM SGT
*/

public interface ClientCallbackOperations 
{
  void startRound (int wordLength, int roundNumber);
  void startGameFailed ();
  void endGame (ModifiedHangman.GameResult gameResultData);
  void endRound (ModifiedHangman.RoundResult roundResultData);
  void proceedToNextRound (int wordLength, int roundNUmber);
} // interface ClientCallbackOperations
