package ModifiedHangman;


/**
* ModifiedHangman/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Saturday, April 26, 2025 3:25:42 AM SGT
*/

public interface ClientCallbackOperations 
{
  void startRound (int wordLength);
  void startGameFailed ();
  void endGame (ModifiedHangman.GameResult gameResult);
  void endRound (ModifiedHangman.RoundResult roundResult);
  void proceedToNextRound (int wordLength);
} // interface ClientCallbackOperations
