package ModifiedHangman;


/**
* ModifiedHangman/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 10:54:55 PM SGT
*/

public interface GameServiceOperations 
{
  void registerCallback (ModifiedHangman.ClientCallback callback, String token) throws ModifiedHangman.PlayerNotLoggedInException;
  ModifiedHangman.GameInfo start_game (String username, String token) throws ModifiedHangman.PlayerNotLoggedInException;
  ModifiedHangman.GuessResponse guessLetter (String username, String gameId, char letter, String token) throws ModifiedHangman.GameNotFoundException, ModifiedHangman.PlayerNotLoggedInException;
  ModifiedHangman.Leaderboard get_leaderboard (String token) throws ModifiedHangman.PlayerNotLoggedInException;
} // interface GameServiceOperations
