package ModifiedHangman;

/**
* ModifiedHangman/GameResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 9:19:59 PM SGT
*/

public final class GameResultHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.GameResult value = null;

  public GameResultHolder ()
  {
  }

  public GameResultHolder (ModifiedHangman.GameResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.GameResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.GameResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.GameResultHelper.type ();
  }

}
