package ModifiedHangman;

/**
* ModifiedHangman/GameNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 10:54:55 PM SGT
*/

public final class GameNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.GameNotFoundException value = null;

  public GameNotFoundExceptionHolder ()
  {
  }

  public GameNotFoundExceptionHolder (ModifiedHangman.GameNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.GameNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.GameNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.GameNotFoundExceptionHelper.type ();
  }

}
