package ModifiedHangman;

/**
* ModifiedHangman/GamePlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 10:54:55 PM SGT
*/

public final class GamePlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.GamePlayer value = null;

  public GamePlayerHolder ()
  {
  }

  public GamePlayerHolder (ModifiedHangman.GamePlayer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.GamePlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.GamePlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.GamePlayerHelper.type ();
  }

}
