package ModifiedHangman;

/**
* ModifiedHangman/GameServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Friday, May 16, 2025 12:00:04 AM SGT
*/

public final class GameServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.GameService value = null;

  public GameServiceHolder ()
  {
  }

  public GameServiceHolder (ModifiedHangman.GameService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.GameServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.GameServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.GameServiceHelper.type ();
  }

}
