package ModifiedHangman;


/**
* ModifiedHangman/GameResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/User/IdeaProjects/9322-Team05_FinProject/CORBA_IDLs/ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 12:11:32 PM SGT
*/

public final class GameResult implements org.omg.CORBA.portable.IDLEntity
{
  public String gameId = null;
  public String gameWinner = null;
  public ModifiedHangman.GamePlayer leaderboard[] = null;

  public GameResult ()
  {
  } // ctor

  public GameResult (String _gameId, String _gameWinner, ModifiedHangman.GamePlayer[] _leaderboard)
  {
    gameId = _gameId;
    gameWinner = _gameWinner;
    leaderboard = _leaderboard;
  } // ctor

} // class GameResult
