package ModifiedHangman;


/**
* ModifiedHangman/GameResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Friday, May 16, 2025 12:00:04 AM SGT
*/

public final class GameResult implements org.omg.CORBA.portable.IDLEntity
{
  public String gameId = null;
  public String gameWinner = null;
  public ModifiedHangman.GamePlayer leaderboard[] = null;

  public GameResult ()
  {
  } // ctor

  public GameResult (String _gameId, String _gameWinner, ModifiedHangman.GamePlayer[] _leaderboard)
  {
    gameId = _gameId;
    gameWinner = _gameWinner;
    leaderboard = _leaderboard;
  } // ctor

} // class GameResult
