package ModifiedHangman;

/**
* ModifiedHangman/GameInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 9:19:59 PM SGT
*/

public final class GameInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.GameInfo value = null;

  public GameInfoHolder ()
  {
  }

  public GameInfoHolder (ModifiedHangman.GameInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.GameInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.GameInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.GameInfoHelper.type ();
  }

}
