package ModifiedHangman;


/**
* ModifiedHangman/GamePlayer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/User/IdeaProjects/9322-Team05_FinProject/CORBA_IDLs/ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 12:11:32 PM SGT
*/

public final class GamePlayer implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public int wins = (int)0;

  public GamePlayer ()
  {
  } // ctor

  public GamePlayer (String _username, int _wins)
  {
    username = _username;
    wins = _wins;
  } // ctor

} // class GamePlayer
