package ModifiedHangman;


/**
* ModifiedHangman/GameInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Friday, May 16, 2025 12:00:04 AM SGT
*/

public final class GameInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String gameId = null;
  public int roundLength = (int)0;
  public int remainingWaitingTime = (int)0;

  public GameInfo ()
  {
  } // ctor

  public GameInfo (String _gameId, int _roundLength, int _remainingWaitingTime)
  {
    gameId = _gameId;
    roundLength = _roundLength;
    remainingWaitingTime = _remainingWaitingTime;
  } // ctor

} // class GameInfo
