package ModifiedHangman;


/**
* ModifiedHangman/GameNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Friday, May 16, 2025 12:00:04 AM SGT
*/

public final class GameNotFoundException extends org.omg.CORBA.UserException
{
  public String message = null;

  public GameNotFoundException ()
  {
    super(GameNotFoundExceptionHelper.id());
  } // ctor

  public GameNotFoundException (String _message)
  {
    super(GameNotFoundExceptionHelper.id());
    message = _message;
  } // ctor


  public GameNotFoundException (String $reason, String _message)
  {
    super(GameNotFoundExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class GameNotFoundException
