package ModifiedHangman;


/**
* ModifiedHangman/GamePlayer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Saturday, April 26, 2025 3:25:42 AM SGT
*/

public final class GamePlayer implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public int wins = (int)0;

  public GamePlayer ()
  {
  } // ctor

  public GamePlayer (String _username, int _wins)
  {
    username = _username;
    wins = _wins;
  } // ctor

} // class GamePlayer
