package ModifiedHangman;


/**
* ModifiedHangman/GameServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Saturday, April 26, 2025 3:25:42 AM SGT
*/

public interface GameServiceOperations 
{
  void registerCallback (ModifiedHangman.ClientCallback callback, String token) throws ModifiedHangman.PlayerNotLoggedInException;
  GameInfo start_game (String username, String token) throws ModifiedHangman.PlayerNotLoggedInException;
  GuessResponse guessLetter (String username, String gameId, char letter, String token) throws ModifiedHangman.GameNotFoundException, ModifiedHangman.PlayerNotLoggedInException;
  Leaderboard get_leaderboard (String token) throws ModifiedHangman.PlayerNotLoggedInException;
} // interface GameServiceOperations
