package ModifiedHangman;

/**
* ModifiedHangman/GuessResponseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/User/IdeaProjects/9322-Team05_FinProject/CORBA_IDLs/ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 12:11:32 PM SGT
*/

public final class GuessResponseHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.GuessResponse value = null;

  public GuessResponseHolder ()
  {
  }

  public GuessResponseHolder (ModifiedHangman.GuessResponse initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.GuessResponseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.GuessResponseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.GuessResponseHelper.type ();
  }

}
