package ModifiedHangman;


/**
* ModifiedHangman/GuessResponse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 9:19:59 PM SGT
*/

public final class GuessResponse implements org.omg.CORBA.portable.IDLEntity
{
  public boolean isWordGuessed = false;
  public String maskedWord = null;
  public ModifiedHangman.AttemptedLetter attemptedLetters[] = null;
  public int remainingAttemptsLeft = (int)0;

  public GuessResponse ()
  {
  } // ctor

  public GuessResponse (boolean _isWordGuessed, String _maskedWord, ModifiedHangman.AttemptedLetter[] _attemptedLetters, int _remainingAttemptsLeft)
  {
    isWordGuessed = _isWordGuessed;
    maskedWord = _maskedWord;
    attemptedLetters = _attemptedLetters;
    remainingAttemptsLeft = _remainingAttemptsLeft;
  } // ctor

} // class GuessResponse
