package ModifiedHangman;


/**
* ModifiedHangman/Leaderboard.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/User/IdeaProjects/9322-Team05_FinProject/CORBA_IDLs/ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 12:11:32 PM SGT
*/

public final class Leaderboard implements org.omg.CORBA.portable.IDLEntity
{
  public ModifiedHangman.GamePlayer players[] = null;

  public Leaderboard ()
  {
  } // ctor

  public Leaderboard (ModifiedHangman.GamePlayer[] _players)
  {
    players = _players;
  } // ctor

} // class Leaderboard
