package ModifiedHangman;


import java.util.List;

/**
* ModifiedHangman/Leaderboard.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Saturday, April 26, 2025 3:25:42 AM SGT
*/

public final class Leaderboard implements org.omg.CORBA.portable.IDLEntity
{
  public ModifiedHangman.GamePlayer[] players = null;

  public Leaderboard ()
  {
  } // ctor

  public Leaderboard (ModifiedHangman.GamePlayer[] _players)
  {
    players = _players;
  } // ctor

  public Leaderboard(List<Player> sortedPlayers) {
    this.players = new ModifiedHangman.GamePlayer[sortedPlayers.size()];

    for (int i = 0; i < sortedPlayers.size(); i++) {
      Player p = sortedPlayers.get(i);
      players[i] = new ModifiedHangman.GamePlayer(
              p.getUsername(),
              p.getWins()
      );
    }
  }

} // class Leaderboard
