package ModifiedHangman;

/**
* ModifiedHangman/LeaderboardHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Saturday, April 26, 2025 3:25:42 AM SGT
*/

public final class LeaderboardHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.Leaderboard value = null;

  public LeaderboardHolder ()
  {
  }

  public LeaderboardHolder (ModifiedHangman.Leaderboard initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.LeaderboardHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.LeaderboardHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.LeaderboardHelper.type ();
  }

}
