package ModifiedHangman;


/**
* ModifiedHangman/LogInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AuthenticationService.idl
* Friday, May 16, 2025 12:00:00 AM SGT
*/

public final class LogInException extends org.omg.CORBA.UserException
{
  public String message = null;

  public LogInException ()
  {
    super(LogInExceptionHelper.id());
  } // ctor

  public LogInException (String _message)
  {
    super(LogInExceptionHelper.id());
    message = _message;
  } // ctor


  public LogInException (String $reason, String _message)
  {
    super(LogInExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class LogInException
