package ModifiedHangman;


/**
* ModifiedHangman/LogInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/User/IdeaProjects/9322-Team05_FinProject/CORBA_IDLs/ModifiedHangman/AuthenticationService.idl
* Thursday, May 15, 2025 12:11:23 PM SGT
*/

public final class LogInException extends org.omg.CORBA.UserException
{
  public String message = null;

  public LogInException ()
  {
    super(LogInExceptionHelper.id());
  } // ctor

  public LogInException (String _message)
  {
    super(LogInExceptionHelper.id());
    message = _message;
  } // ctor


  public LogInException (String $reason, String _message)
  {
    super(LogInExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class LogInException
