package ModifiedHangman;


/**
* ModifiedHangman/LogInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AuthenticationService.idl
* Saturday, April 26, 2025 3:26:15 AM SGT
*/

public final class LogInException extends org.omg.CORBA.UserException
{

  public LogInException ()
  {
    super(LogInExceptionHelper.id());
  } // ctor


  public LogInException (String $reason)
  {
    super(LogInExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class LogInException
