package ModifiedHangman;

/**
* ModifiedHangman/LogInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AuthenticationService.idl
* Saturday, April 26, 2025 3:26:15 AM SGT
*/

public final class LogInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.LogInException value = null;

  public LogInExceptionHolder ()
  {
  }

  public LogInExceptionHolder (ModifiedHangman.LogInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.LogInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.LogInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.LogInExceptionHelper.type ();
  }

}
