package ModifiedHangman;

/**
* ModifiedHangman/PlayerNotLoggedInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Friday, May 16, 2025 12:00:04 AM SGT
*/

public final class PlayerNotLoggedInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.PlayerNotLoggedInException value = null;

  public PlayerNotLoggedInExceptionHolder ()
  {
  }

  public PlayerNotLoggedInExceptionHolder (ModifiedHangman.PlayerNotLoggedInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.PlayerNotLoggedInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.PlayerNotLoggedInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.PlayerNotLoggedInExceptionHelper.type ();
  }

}
