package ModifiedHangman;


/**
* ModifiedHangman/PlayerListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AdminService.idl
* Thursday, May 15, 2025 10:54:58 PM SGT
*/

public final class PlayerListHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.Player value[] = null;

  public PlayerListHolder ()
  {
  }

  public PlayerListHolder (ModifiedHangman.Player[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.PlayerListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.PlayerListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.PlayerListHelper.type ();
  }

}
