package ModifiedHangman;


/**
* ModifiedHangman/PlayerNotLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Friday, May 16, 2025 12:00:04 AM SGT
*/

public final class PlayerNotLoggedInException extends org.omg.CORBA.UserException
{
  public String message = null;

  public PlayerNotLoggedInException ()
  {
    super(PlayerNotLoggedInExceptionHelper.id());
  } // ctor

  public PlayerNotLoggedInException (String _message)
  {
    super(PlayerNotLoggedInExceptionHelper.id());
    message = _message;
  } // ctor


  public PlayerNotLoggedInException (String $reason, String _message)
  {
    super(PlayerNotLoggedInExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class PlayerNotLoggedInException
