package ModifiedHangman;


/**
* ModifiedHangman/PlayerNotLoggedInException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/AuthenticationService.idl
* Saturday, April 26, 2025 3:26:15 AM SGT
*/

public final class PlayerNotLoggedInException extends org.omg.CORBA.UserException
{

  public PlayerNotLoggedInException ()
  {
    super(PlayerNotLoggedInExceptionHelper.id());
  } // ctor


  public PlayerNotLoggedInException (String $reason)
  {
    super(PlayerNotLoggedInExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class PlayerNotLoggedInException
