package ModifiedHangman;

/**
* ModifiedHangman/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/User/IdeaProjects/9322-Team05_FinProject/CORBA_IDLs/ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 12:11:32 PM SGT
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public ModifiedHangman.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (ModifiedHangman.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModifiedHangman.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModifiedHangman.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModifiedHangman.PlayerHelper.type ();
  }

}
