package ModifiedHangman;


/**
* ModifiedHangman/RoundResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/User/IdeaProjects/9322-Team05_FinProject/CORBA_IDLs/ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 12:11:32 PM SGT
*/

public final class RoundResult implements org.omg.CORBA.portable.IDLEntity
{
  public String gameId = null;
  public String roundWinner = null;
  public int roundWinnerTime = (int)0; // TODO : remove this datafield
  public String statusMessage = null;

  // it can be "You've done it in 20 seconds" or "You did not guessed it" or "You won this round"
  public ModifiedHangman.GamePlayer currentGameLeaderboard[] = null;

  public RoundResult ()
  {
  } // ctor

  public RoundResult (String _gameId, String _roundWinner, int _roundWinnerTime, String _statusMessage, ModifiedHangman.GamePlayer[] _currentGameLeaderboard)
  {
    gameId = _gameId;
    roundWinner = _roundWinner;
    roundWinnerTime = _roundWinnerTime;
    statusMessage = _statusMessage;
    currentGameLeaderboard = _currentGameLeaderboard;
  } // ctor

} // class RoundResult
