package ModifiedHangman;


/**
* ModifiedHangman/RoundResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Thursday, May 15, 2025 10:54:55 PM SGT
*/

public final class RoundResult implements org.omg.CORBA.portable.IDLEntity
{
  public String gameId = null;
  public int roundNumber = (int)0;
  public ModifiedHangman.GamePlayer roundWinner = null;
  public String wordToGuess = null;
  public String statusMessage = null;

  // it can be "You've done it in 20 seconds" or "You did not guessed it" or "You won this round"
  public ModifiedHangman.GamePlayer currentGameLeaderboard[] = null;

  public RoundResult ()
  {
  } // ctor

  public RoundResult (String _gameId, int _roundNumber, ModifiedHangman.GamePlayer _roundWinner, String _wordToGuess, String _statusMessage, ModifiedHangman.GamePlayer[] _currentGameLeaderboard)
  {
    gameId = _gameId;
    roundNumber = _roundNumber;
    roundWinner = _roundWinner;
    wordToGuess = _wordToGuess;
    statusMessage = _statusMessage;
    currentGameLeaderboard = _currentGameLeaderboard;
  } // ctor

} // class RoundResult
