package ModifiedHangman;


/**
* ModifiedHangman/RoundResultHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModifiedHangman/GameService.idl
* Saturday, April 26, 2025 3:25:42 AM SGT
*/

abstract public class RoundResultHelper
{
  private static String  _id = "IDL:ModifiedHangman/RoundResult:1.0";

  public static void insert (org.omg.CORBA.Any a, ModifiedHangman.RoundResult that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ModifiedHangman.RoundResult extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "gameId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "roundWinner",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "roundWinnerTime",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "statusMessage",
            _tcOf_members0,
            null);
          _tcOf_members0 = ModifiedHangman.GamePlayerHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "currentGameLeaderboard",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ModifiedHangman.RoundResultHelper.id (), "RoundResult", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ModifiedHangman.RoundResult read (org.omg.CORBA.portable.InputStream istream)
  {
    ModifiedHangman.RoundResult value = new ModifiedHangman.RoundResult ();
    value.gameId = istream.read_string ();
    value.roundWinner = istream.read_string ();
    value.roundWinnerTime = istream.read_long ();
    value.statusMessage = istream.read_string ();
    int _len0 = istream.read_long ();
    value.currentGameLeaderboard = new ModifiedHangman.GamePlayer[_len0];
    for (int _o1 = 0;_o1 < value.currentGameLeaderboard.length; ++_o1)
      value.currentGameLeaderboard[_o1] = ModifiedHangman.GamePlayerHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ModifiedHangman.RoundResult value)
  {
    ostream.write_string (value.gameId);
    ostream.write_string (value.roundWinner);
    ostream.write_long (value.roundWinnerTime);
    ostream.write_string (value.statusMessage);
    ostream.write_long (value.currentGameLeaderboard.length);
    for (int _i0 = 0;_i0 < value.currentGameLeaderboard.length; ++_i0)
      ModifiedHangman.GamePlayerHelper.write (ostream, value.currentGameLeaderboard[_i0]);
  }

}
