# DO NOT EDIT THIS FILE!
#
# Python module ModifiedHangman__POA generated by omniidl

import omniORB
omniORB.updateModule("ModifiedHangman__POA")

# ** 1. Stub files contributing to this module
import AuthenticationService_idl
import GameService_idl
import AdminService_idl

# ** 2. Sub-modules

# ** 3. End
